version: '3.1'
services:
  postgresql:
    image: postgres
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb